### ISSUE TITLE
Split out locality/ballot page from the ballot detail page

### ISSUE THREAD

**Issue by adborden** [adborden/odca-oakland#32]
Mockups actually call for a separate locality/ballot page from the ballot item detail:
!['sm-desktop-3-local_list-standard-reducedscope'](https://cloud.githubusercontent.com/assets/6467815/18463165/05610ef6-793d-11e6-9144-cf37361a6f30.png)

**Comment by elinaru** [comment]
In included this mock-up in case we didn't have time to implement the master/detail layout. But since we have, this mock is now obsolete. I'm going to remove it when I update the mock-ups next.

**Comment by elinaru** [comment]
In included this mock-up in case we didn't have time to implement the master/detail layout. But since we have, this mock is now obsolete. I'm going to remove it when I update the mock-ups next.
